services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: solar_db

    ports:
      - "5432:5432"

    volumes:
      - tsdb_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2

    ports:
      - "1883:1883"

    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  grafana:
    image: grafana/grafana:latest

    ports:
      - "3000:3000"

    volumes:
      - grafana_data:/var/lib/grafana

    depends_on:
      - timescaledb

volumes:
  tsdb_data:
  grafana_data: